### ISSUE TITLE
python3.7 is hard-coded in PKGBUILD 

### ISSUE THREAD

**Issue by Poikilos** [samurai-ide/samurai-ide#3]

**Comment by benmoran56** [comment]
I made a PR to fix this. 
https://github.com/samurai-ide/samurai-ide/pull/6

Samurai-IDE is currently still broken on the latest Arch though, but I made another PR to start updating it.

**Comment by benmoran56** [comment]
This should be OK to close now, since the PR was merged.

**Comment by Poikilos** [comment]
Ok, fixed in [f16a298](https://github.com/samurai-ide/samurai-ide/pull/6/commits/f16a298a50b53af06edf77ab91e9b8661276a69b)
